l1_url = ""
l1_receipt_confirm_timeout = "30s"
l1_confirm_blocks = 1
scc_contract_address = ""
tss_group_contract_address = ""
tss_staking_slash_contract_address = ""

timed_task_interval = "10s"
l1_start_block_number = 1
miss_signed_number = 5

[manager]

ws_addr = "tcp://0.0.0.0:8081"
http_addr = ":8080"
jwt_secret = ""
db_dir = "/root/tss-manager/db"

keygen_timeout = "1m"
cpk_confirm_timeout = "10s"
ask_timeout = "1m"
sign_timeout = "2m"
private_key = ""
